In [99]:
import pandas as pd
import numpy as np

## Load Data

In [100]:
data = pd.read_csv("Best_Books_Ever.csv")
print(data.columns)
# data

Index(['bookId', 'title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price'],
      dtype='object')

## Drop Unnecesary Columns And Change NaN to self-concluding when a book doesnt belong to a serie

In [101]:
data_col_dropped = data.drop("characters", axis=1).drop("numRatings", axis=1).drop("publisher", axis=1).drop("bbeScore", axis=1).drop("bbeVotes", axis=1).drop("bookFormat", axis=1).drop("firstPublishDate", axis=1).drop("description", axis=1).drop("bookId", axis=1).drop("isbn", axis=1).drop("edition", axis=1).drop("awards", axis=1).drop("ratingsByStars", axis=1).drop("setting", axis=1).drop("coverImg", axis=1)
data_col_dropped["series"] = data_col_dropped["series"].fillna('standalone')
data_col_dropped

,title,series,author,rating,language,genres,pages,publishDate,likedPercent,price
0,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,English,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,96.0,5.09
1,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,English,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,98.0,7.38
2,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,English,"['Classics', 'Fiction', 'Historical Fiction', ...",324,05/23/06,95.0,NaN
3,Pride and Prejudice,standalone,"Jane Austen, Anna Quindlen (Introduction)",4.26,English,"['Classics', 'Fiction', 'Romance', 'Historical...",279,10/10/00,94.0,NaN
4,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,English,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,78.0,2.1
...,...,...,...,...,...,...,...,...,...,...
52473,Fractured,Fateful #2,Cheri Schmidt (Goodreads Author),4.00,English,"['Vampires', 'Paranormal', 'Young Adult', 'Rom...",0,May 28th 2011,94.0,NaN
52474,Anasazi,Sense of Truth #2,Emma Michaels,4.19,English,"['Mystery', 'Young Adult']",190,August 5th 2011,95.0,NaN
52475,Marked,Soul Guardians #1,Kim Richardson (Goodreads Author),3.70,English,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",280,March 18th 2011,84.0,7.37
52476,Wayward Son,standalone,"Tom Pollack (Goodreads Author), John Loftus (G...",3.85,English,"['Fiction', 'Mystery', 'Historical Fiction', '...",507,September 1st 2011,90.0,2.86
52477,Daughter of Helaman,Stripling Warrior #1,Misty Moncur (Goodreads Author),4.02,English,"['Lds Fiction', 'Historical Fiction', 'Young A...",201,May 8th 2011,90.0,5.20

### Drop every row that has some NaN or null features and filter books that are in English and from them, remove books that doesnt have any genre

In [102]:
data_NaN_dropped = data_col_dropped.dropna()
data_english_sorted = data_NaN_dropped[(data_NaN_dropped["language"] == "English")]
data_english_sorted = data_english_sorted.drop("language", axis=1)
data_genres_not_empty = data_english_sorted[data_english_sorted["genres"].apply(lambda x: x.removeprefix('[').removesuffix(']') != '')]
data_genres_not_empty

,title,series,author,rating,genres,pages,publishDate,likedPercent,price
0,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,96.0,5.09
1,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,98.0,7.38
4,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,78.0,2.1
5,The Book Thief,standalone,Markus Zusak (Goodreads Author),4.37,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,96.0,3.8
6,Animal Farm,standalone,"George Orwell, Russell Baker (Preface), C.M. W...",3.95,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,91.0,4.42
...,...,...,...,...,...,...,...,...,...
52470,Attracted to Fire,standalone,DiAnn Mills (Goodreads Author),4.14,"['Christian Fiction', 'Christian', 'Suspense',...",416,October 1st 2011,95.0,5.55
52472,Unbelievable,Port Fare #2,Sherry Gammon (Goodreads Author),4.16,"['Romance', 'Young Adult', 'Contemporary', 'Co...",360,April 11th 2013,94.0,19.18
52475,Marked,Soul Guardians #1,Kim Richardson (Goodreads Author),3.70,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",280,March 18th 2011,84.0,7.37
52476,Wayward Son,standalone,"Tom Pollack (Goodreads Author), John Loftus (G...",3.85,"['Fiction', 'Mystery', 'Historical Fiction', '...",507,September 1st 2011,90.0,2.86
52477,Daughter of Helaman,Stripling Warrior #1,Misty Moncur (Goodreads Author),4.02,"['Lds Fiction', 'Historical Fiction', 'Young A...",201,May 8th 2011,90.0,5.20

## Simple Query to search by author

In [103]:
data_genres_not_empty[data_genres_not_empty["author"].str.contains("Patrick Rothfuss", case=False, na=False)].sort_values("likedPercent", ascending=False)

,title,series,author,rating,genres,pages,publishDate,likedPercent,price
308,The Wise Man's Fear,The Kingkiller Chronicle #2,Patrick Rothfuss (Goodreads Author),4.56,"['Fantasy', 'Fiction', 'Epic Fantasy', 'High F...",994,03/01/11,98.0,16.37
110,The Name of the Wind,The Kingkiller Chronicle #1,Patrick Rothfuss (Goodreads Author),4.53,"['Fantasy', 'Fiction', 'Epic Fantasy', 'High F...",662,04/28/07,96.0,9.36
2385,The Slow Regard of Silent Things,The Kingkiller Chronicle #2.5,"Patrick Rothfuss (Goodreads Author), Nate Tayl...",3.90,"['Fantasy', 'Fiction', 'Short Stories', 'High ...",159,October 28th 2014,89.0,9.58

## Simplify authors

In [104]:
def extract_author(authors: str) -> str:
  """Author filter

  Args:
      authors (str): some books could contain more than 1 author

  Returns:
      str: the first author that appears
  """
  author = authors.split(', ')[0]
  if "(" not in author:
    return author
  else:
    return author.split(' (')[0]

In [105]:
data_genres_not_empty["author"] = data_genres_not_empty["author"].apply(extract_author)
data_genres_not_empty

C:\Users\victo\AppData\Local\Temp\ipykernel_28272\2177613293.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_genres_not_empty["author"] = data_genres_not_empty["author"].apply(extract_author)

,title,series,author,rating,genres,pages,publishDate,likedPercent,price
0,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,96.0,5.09
1,Harry Potter and the Order of the Phoenix,Harry Potter #5,J.K. Rowling,4.50,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,98.0,7.38
4,Twilight,The Twilight Saga #1,Stephenie Meyer,3.60,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,78.0,2.1
5,The Book Thief,standalone,Markus Zusak,4.37,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,96.0,3.8
6,Animal Farm,standalone,George Orwell,3.95,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,91.0,4.42
...,...,...,...,...,...,...,...,...,...
52470,Attracted to Fire,standalone,DiAnn Mills,4.14,"['Christian Fiction', 'Christian', 'Suspense',...",416,October 1st 2011,95.0,5.55
52472,Unbelievable,Port Fare #2,Sherry Gammon,4.16,"['Romance', 'Young Adult', 'Contemporary', 'Co...",360,April 11th 2013,94.0,19.18
52475,Marked,Soul Guardians #1,Kim Richardson,3.70,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",280,March 18th 2011,84.0,7.37
52476,Wayward Son,standalone,Tom Pollack,3.85,"['Fiction', 'Mystery', 'Historical Fiction', '...",507,September 1st 2011,90.0,2.86
52477,Daughter of Helaman,Stripling Warrior #1,Misty Moncur,4.02,"['Lds Fiction', 'Historical Fiction', 'Young A...",201,May 8th 2011,90.0,5.20

## Clean series

In [106]:
def clean_series(series: str) -> str:
  """Series filter

  Args:
      series (str): some series contains the book index on the serie

  Returns:
      str: series without book index
  """
  if "#" in series:
    return series.split(' #')[0]
  return series

In [107]:
data_genres_not_empty["series"] = data_genres_not_empty["series"].apply(clean_series)
data_genres_not_empty

C:\Users\victo\AppData\Local\Temp\ipykernel_28272\1243019038.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_genres_not_empty["series"] = data_genres_not_empty["series"].apply(clean_series)

,title,series,author,rating,genres,pages,publishDate,likedPercent,price
0,The Hunger Games,The Hunger Games,Suzanne Collins,4.33,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,96.0,5.09
1,Harry Potter and the Order of the Phoenix,Harry Potter,J.K. Rowling,4.50,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,98.0,7.38
4,Twilight,The Twilight Saga,Stephenie Meyer,3.60,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,78.0,2.1
5,The Book Thief,standalone,Markus Zusak,4.37,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,96.0,3.8
6,Animal Farm,standalone,George Orwell,3.95,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,91.0,4.42
...,...,...,...,...,...,...,...,...,...
52470,Attracted to Fire,standalone,DiAnn Mills,4.14,"['Christian Fiction', 'Christian', 'Suspense',...",416,October 1st 2011,95.0,5.55
52472,Unbelievable,Port Fare,Sherry Gammon,4.16,"['Romance', 'Young Adult', 'Contemporary', 'Co...",360,April 11th 2013,94.0,19.18
52475,Marked,Soul Guardians,Kim Richardson,3.70,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",280,March 18th 2011,84.0,7.37
52476,Wayward Son,standalone,Tom Pollack,3.85,"['Fiction', 'Mystery', 'Historical Fiction', '...",507,September 1st 2011,90.0,2.86
52477,Daughter of Helaman,Stripling Warrior,Misty Moncur,4.02,"['Lds Fiction', 'Historical Fiction', 'Young A...",201,May 8th 2011,90.0,5.20

## Extract every author

In [108]:
authors = set()
for book in data_genres_not_empty.values:
  book_authors : str = book[2]
  for author in book_authors.split(', '):
    if "(" in author and "(Goodreads Author)" not in author:
      continue
    authors.add(author.removesuffix(" (Goodreads Author)"))
print(f'Total Authors: {len(authors)}')

Total Authors: 13914

## Simple example that show every book from a random author

In [109]:
from random import choice as rdc
author = rdc(list(authors))
print(author)
data_genres_not_empty[data_genres_not_empty["author"].str.contains(author, case=False, na=False)]

Rob Thomas

,title,series,author,rating,genres,pages,publishDate,likedPercent,price
40190,The Thousand-Dollar Tan Line,Veronica Mars,Rob Thomas,3.99,"['Mystery', 'Fiction', 'Audiobook', 'Crime', '...",324,March 25th 2014,94.0,2.33

## Create the column Publish Year and extract the year from Publish Date

In [110]:
def extract_year_from_date(date: str) -> str:
  """Extract the year from the publish date

  Args:
      date (str): Publish Date

  Returns:
      str: Year from the publish date or 'remove' if the publish date its not a date
  """
  if "/" in date:
    year = date[-2:]
    return f"20{year}" if int(year) < 24 else f"19{year}"
  else:
    if not date[-4:].isdecimal():
      return 'remove'
    return date[-4:]

In [111]:
data_genres_not_empty['publishYear'] = data_genres_not_empty['publishDate'].apply(extract_year_from_date)
data_genres_not_empty = data_genres_not_empty[data_genres_not_empty['publishYear'] != 'remove']
data_genres_not_empty = data_genres_not_empty[['title', 'series', 'author', 'genres', 'pages', 'publishDate', 'publishYear', 'rating', 'likedPercent', 'price']]
data_genres_not_empty

C:\Users\victo\AppData\Local\Temp\ipykernel_28272\3290548565.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_genres_not_empty['publishYear'] = data_genres_not_empty['publishDate'].apply(extract_year_from_date)

,title,series,author,genres,pages,publishDate,publishYear,rating,likedPercent,price
0,The Hunger Games,The Hunger Games,Suzanne Collins,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,2008,4.33,96.0,5.09
1,Harry Potter and the Order of the Phoenix,Harry Potter,J.K. Rowling,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,2004,4.50,98.0,7.38
4,Twilight,The Twilight Saga,Stephenie Meyer,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,2006,3.60,78.0,2.1
5,The Book Thief,standalone,Markus Zusak,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,2006,4.37,96.0,3.8
6,Animal Farm,standalone,George Orwell,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,1996,3.95,91.0,4.42
...,...,...,...,...,...,...,...,...,...,...
52470,Attracted to Fire,standalone,DiAnn Mills,"['Christian Fiction', 'Christian', 'Suspense',...",416,October 1st 2011,2011,4.14,95.0,5.55
52472,Unbelievable,Port Fare,Sherry Gammon,"['Romance', 'Young Adult', 'Contemporary', 'Co...",360,April 11th 2013,2013,4.16,94.0,19.18
52475,Marked,Soul Guardians,Kim Richardson,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",280,March 18th 2011,2011,3.70,84.0,7.37
52476,Wayward Son,standalone,Tom Pollack,"['Fiction', 'Mystery', 'Historical Fiction', '...",507,September 1st 2011,2011,3.85,90.0,2.86
52477,Daughter of Helaman,Stripling Warrior,Misty Moncur,"['Lds Fiction', 'Historical Fiction', 'Young A...",201,May 8th 2011,2011,4.02,90.0,5.20

## Some pages has the text '1 page' instead of the num of pages

In [112]:
data_genres_not_empty = data_genres_not_empty[data_genres_not_empty['pages'] != '1 page']

## Clean price

In [113]:
def clean_price(price: str) -> str:
  """Clean price

  Args:
      price (str): some prices has more than 1 dot

  Returns:
      str: return price with only 1 dot
  """
  if price.count('.') > 1:
    parts = price.split('.')
    return ''.join(parts[:-1]) + '.' + parts[-1]
  return price

In [114]:
data_genres_not_empty['price'] = data_genres_not_empty['price'].apply(clean_price)
data_genres_not_empty

C:\Users\victo\AppData\Local\Temp\ipykernel_28272\149482157.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_genres_not_empty['price'] = data_genres_not_empty['price'].apply(clean_price)

,title,series,author,genres,pages,publishDate,publishYear,rating,likedPercent,price
0,The Hunger Games,The Hunger Games,Suzanne Collins,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",374,09/14/08,2008,4.33,96.0,5.09
1,Harry Potter and the Order of the Phoenix,Harry Potter,J.K. Rowling,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...",870,09/28/04,2004,4.50,98.0,7.38
4,Twilight,The Twilight Saga,Stephenie Meyer,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...",501,09/06/06,2006,3.60,78.0,2.1
5,The Book Thief,standalone,Markus Zusak,"['Historical Fiction', 'Fiction', 'Young Adult...",552,03/14/06,2006,4.37,96.0,3.8
6,Animal Farm,standalone,George Orwell,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",141,04/28/96,1996,3.95,91.0,4.42
...,...,...,...,...,...,...,...,...,...,...
52470,Attracted to Fire,standalone,DiAnn Mills,"['Christian Fiction', 'Christian', 'Suspense',...",416,October 1st 2011,2011,4.14,95.0,5.55
52472,Unbelievable,Port Fare,Sherry Gammon,"['Romance', 'Young Adult', 'Contemporary', 'Co...",360,April 11th 2013,2013,4.16,94.0,19.18
52475,Marked,Soul Guardians,Kim Richardson,"['Fantasy', 'Young Adult', 'Paranormal', 'Ange...",280,March 18th 2011,2011,3.70,84.0,7.37
52476,Wayward Son,standalone,Tom Pollack,"['Fiction', 'Mystery', 'Historical Fiction', '...",507,September 1st 2011,2011,3.85,90.0,2.86
52477,Daughter of Helaman,Stripling Warrior,Misty Moncur,"['Lds Fiction', 'Historical Fiction', 'Young A...",201,May 8th 2011,2011,4.02,90.0,5.20

In [115]:
def genres_to_list(genres: str) -> list:
  list_of_genres = genres.removeprefix('[').removesuffix(']').split(', ')
  return list(map(lambda s: s[1:][:-1], list_of_genres))

In [116]:
data_genres_not_empty["genres"] = data_genres_not_empty["genres"].apply(genres_to_list)

C:\Users\victo\AppData\Local\Temp\ipykernel_28272\4231857731.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_genres_not_empty["genres"] = data_genres_not_empty["genres"].apply(genres_to_list)

In [117]:
data_genres_not_empty = data_genres_not_empty[data_genres_not_empty['price'].astype(float) < 1000]
data_genres_not_empty

,title,series,author,genres,pages,publishDate,publishYear,rating,likedPercent,price
0,The Hunger Games,The Hunger Games,Suzanne Collins,"[Young Adult, Fiction, Dystopia, Fantasy, Scie...",374,09/14/08,2008,4.33,96.0,5.09
1,Harry Potter and the Order of the Phoenix,Harry Potter,J.K. Rowling,"[Fantasy, Young Adult, Fiction, Magic, Childre...",870,09/28/04,2004,4.50,98.0,7.38
4,Twilight,The Twilight Saga,Stephenie Meyer,"[Young Adult, Fantasy, Romance, Vampires, Fict...",501,09/06/06,2006,3.60,78.0,2.1
5,The Book Thief,standalone,Markus Zusak,"[Historical Fiction, Fiction, Young Adult, His...",552,03/14/06,2006,4.37,96.0,3.8
6,Animal Farm,standalone,George Orwell,"[Classics, Fiction, Dystopia, Fantasy, Literat...",141,04/28/96,1996,3.95,91.0,4.42
...,...,...,...,...,...,...,...,...,...,...
52470,Attracted to Fire,standalone,DiAnn Mills,"[Christian Fiction, Christian, Suspense, Roman...",416,October 1st 2011,2011,4.14,95.0,5.55
52472,Unbelievable,Port Fare,Sherry Gammon,"[Romance, Young Adult, Contemporary, Contempor...",360,April 11th 2013,2013,4.16,94.0,19.18
52475,Marked,Soul Guardians,Kim Richardson,"[Fantasy, Young Adult, Paranormal, Angels, Rom...",280,March 18th 2011,2011,3.70,84.0,7.37
52476,Wayward Son,standalone,Tom Pollack,"[Fiction, Mystery, Historical Fiction, Adventu...",507,September 1st 2011,2011,3.85,90.0,2.86
52477,Daughter of Helaman,Stripling Warrior,Misty Moncur,"[Lds Fiction, Historical Fiction, Young Adult,...",201,May 8th 2011,2011,4.02,90.0,5.20

## Save dataset for DB and for Training

In [118]:
data_clean = data_genres_not_empty.copy()
# data_clean = data_genres_not_empty.head(50)
data_clean = data_clean.sample(frac=1).reset_index(drop=True)
data_clean.to_csv('BestBooksEverClean.csv', index=None)
data_to_train = data_clean.drop("publishDate", axis=1)
data_to_train.to_csv('BestBooksEverClean_train_dataset.csv', index=None)
data_clean

,title,series,author,genres,pages,publishDate,publishYear,rating,likedPercent,price
0,Ballet Shoes,Shoes,Noel Streatfeild,"[Childrens, Classics, Fiction, Middle Grade, Y...",233,September 2003,2003,4.06,94.0,3.47
1,An Appetite for Violets,standalone,Martine Bailey,"[Historical Fiction, Mystery, Fiction, Histori...",400,January 13th 2015,2015,3.71,91.0,3.99
2,The Memory Artists,standalone,Jeffrey Moore,"[Fiction, Contemporary, Psychology, Drama, Can...",336,February 21st 2006,2006,3.71,90.0,5.22
3,Why I Left Goldman Sachs: A Wall Street Story,standalone,Greg Smith,"[Nonfiction, Business, Finance, Economics, Bio...",380,October 26th 2012,2012,3.70,91.0,19.88
4,Earthly Powers,standalone,Anthony Burgess,"[Fiction, Classics, Literature, Religion, Brit...",649,May 6th 2004,2004,4.15,93.0,2.92
...,...,...,...,...,...,...,...,...,...,...
31794,Pagan Babies,standalone,Elmore Leonard,"[Fiction, Crime, Mystery, Thriller, Novels, Su...",334,January 2002,2002,3.53,90.0,1.67
31795,Rain,Undead Rain,Shaun Harbinger,"[Zombies, Horror, Fiction, Post Apocalyptic, A...",228,March 7th 2014,2014,3.74,87.0,11.45
31796,"Liar, Temptress, Soldier, Spy: Four Women Unde...",standalone,Karen Abbott,"[Nonfiction, History, Civil War, Biography, Hi...",513,September 2nd 2014,2014,3.74,90.0,1.79
31797,Fault Lines: How Hidden Fractures Still Threat...,standalone,Raghuram G. Rajan,"[Economics, Nonfiction, Finance, Business, Pol...",260,May 1st 2010,2010,4.11,95.0,2.55
31798,Lady of Hay,standalone,Barbara Erskine,"[Historical Fiction, Historical, Fiction, Time...",600,March 13th 2001,2001,4.05,91.0,3.08